language: java

jdk:
  - openjdk15

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install

deploy:
  provider: heroku
  api_key: 2fcf171d-0ac3-4e9c-847f-c78bfb9d005a
  app: frontend-build
