language: java

jdk:
  - openjdk15

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install

deploy:
  provider: heroku
  api_key: ${{ secrets.HEROKU_API_KEY }}
  app:
    main: frontend-build
